name: build-and-docker-publish

on:
  push:
    branches: [core]
  schedule:
    - cron: '*/5 * * * 0,6'

jobs:
  build-and-docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: booniepepper
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: make release
        run: |
          make release
